### ISSUE TITLE
Mark other players with your suspected influence

### ISSUE THREAD

**Issue by adevick** [lounsbrough/coup-online#172]
### Feature Request 
Would be cool like in Sudoku, where you can mark a box with suspected numbers you think that square could be, but with influences. a user could mark other players with what they think that user has.  Maybe a small batch icon on the top left with a smaller version of the influence Icon you think they have.

**Comment by lounsbrough** [comment]
I like this idea, and interestingly I was wondering about the possibility of showing claimed influences while playing this morning. This idea is probably better than that, because your guess will likely differ from the actual claimed influences.

**Comment by lounsbrough** [comment]
Yeah I think that's the player's responsibility
